export const KNOWN_VECTOR_ICONS = new Set([
  'v2ex',
  'feedly',
  'twitter',
  'metaso',
  'zhihu',
  'bilibili',
  'youtube',
  'gemini',
  'aistudio',
  'gmail',
  'yuanbao',
  'tongyi',
  'smzdm',
  'nga',
  'github',
  'chatgpt',
  'homepage',
  'cloudflare',
  'rn-proxy',
  'cpa-keeper',
  'cli-proxy',
  'cpa-usage',
  'codex-usage',
  'linuxdo',
  'taobao',
  'jd',
  'weibo',
  'coze',
  'douban',
  '10jqka',
  'doubao',
  'xiaohongshu',
  'settings',
  'plus',
  'tinyauth',
  'beszel',
  'komodo',
  'sublinkpro',
  '3x-ui',
  'claude',
  'deepseek',
  'kimi',
  'qwen',
  'perplexity',
  'google',
  'google-drive',
  'chrome-store',
  'vercel',
  'xueqiu',
  'manmanbuy',
])

export function hasVectorIcon(name?: string): boolean {
  if (!name) return false
  return KNOWN_VECTOR_ICONS.has(name)
}
